export enum MatchEventDTOType {
	CHAMPION_KILL = 'CHAMPION_KILL',
	WARD_PLACED = 'WARD_PLACED',
	WARD_KILL = 'WARD_KILL',
	BUILDING_KILL = 'BUILDING_KILL',
	ELITE_MONSTER_KILL = 'ELITE_MONSTER_KILL',
	ITEM_PURCHASED = 'ITEM_PURCHASED',
	ITEM_SOLD = 'ITEM_SOLD',
	ITEM_DESTROYED = 'ITEM_DESTROYED',
	ITEM_UNDO = 'ITEM_UNDO',
	SKILL_LEVEL_UP = 'SKILL_LEVEL_UP',
	ASCENDED_EVENT = 'ASCENDED_EVENT',
	CAPTURE_POINT = 'CAPTURE_POINT',
	PORO_KING_SUMMON = 'PORO_KING_SUMMON'
}